import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Layout from "./barLayout";
import { Toaster } from 'react-hot-toast'
import { PreviousUrlProvider } from "./others/prevURL/page";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <PreviousUrlProvider>
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <main>
          <Toaster position="top-center" />
          <Layout />
          {children}
        </main>
      </body>
    </html>
    </PreviousUrlProvider>
  );
}
